[package]
name = "rerun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
notify = "6.1.1"
notify-debouncer-full = "0.3.1"
